backend:
  name: github
  repo: lilnoun1112/theworks
  branch: main
  base_url: https://netlify-cms-oauth-delta.vercel.app

media_folder: static/img
public_folder: /img

collections:
  - name: "publications"
    label: "Publications"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "tag", label: "Tag", widget: "string" }
      - { name: "preview", label: "Preview", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }




