backend:
  name: github
  repo: lilnoun1112/theworks
  branch: main
  token: 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

media_folder: static/img
public_folder: /img

collections:
  - name: "publications"
    label: "Publications"
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "tag", label: "Tag", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }




