backend:
  name: [github | gitlab]
  repo: adrian-ub/adrian-ub # Path to your Github/Gitlab repository
  branch: main # Branch to update
  base_url: https://netlify-cms.adrianub.vercel.app

media_folder: static/img
public_folder: /img

collections:
  - name: "publications"
    label: "Publications"
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "tag", label: "Tag", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }




