backend:
  name: github
  repo: lilnoun1112/theworks
  branch: main
  base_url: https://netlify-cms-oauth-delta.vercel.app

media_folder: /static/img
public_folder: /img

collections:
  - name: "publications"
    label: "Publications"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "tags", label: "Tag", widget: "select", multiple: false, options: ["Peer-reviewed", "Preprint", "Code", "Patent", "Project", "Whitepaper"] }
      - { name: "featured", label: "Featured", widget: "boolean", default: "false", required: false}
      - { name: "preview", label: "Preview", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown", required: false}
      - { name: "fullarticle", label: "Full article URL", widget: "string", required: false }
  - name: "team"
    label: "Team"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "position", label: "Position", widget: "string" }
      - { name: "field", label: "Field", widget: "string" }
      - { name: "affiliation", label: "Affiliation", widget: "string" }
      - { name: "image", label: "Image", widget: "image", media_folder: "/static/teamimages"}
      - { name: "cvlink", label: "CV URL", widget: "string", required: false}
      - { name: "cvfile", label: "CV Upload", widget: "file", media_folder: "/static/cvs", required: false}


